language: python
python:
  - "2.7"
before-install: 
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
- pip install -r requirements.txt
script:
- pytest -s homework_tests_test_game.py
- coverage run -m --source=. pytest homework_tests_test_game.py